# Generated by Django 5.0.1 on 2024-01-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_authuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('avto', '0002_alter_avto_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthUser',
            new_name='CustomUser',
        ),
    ]
