# Generated by Django 5.0.1 on 2024-01-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_rename_customuser_authuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='authuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='username',
        ),
    ]
