# Generated by Django 5.0.1 on 2024-01-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_authuser_options_alter_authuser_managers_and_more'),
        ('avto', '0004_alter_avto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
