# Generated by Django 5.0.1 on 2024-01-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_authuser_options_alter_authuser_managers_and_more'),
        ('avto', '0002_alter_avto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avto_user', to='User.authuser', verbose_name='User'),
        ),
    ]
