# Generated by Django 5.0.1 on 2024-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0005_avto_dvigatel_avto_savdolashuv_avto_xolati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='yana',
            field=models.TextField(verbose_name='qushimcha'),
        ),
    ]
