# Generated by Django 5.0.1 on 2024-01-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0006_alter_avto_yana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='dvigatel',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Dvigatel Hajmi'),
        ),
    ]
