# Generated by Django 5.0.1 on 2024-01-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0009_alter_avto_yana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='savdolashuv',
            field=models.CharField(choices=[('Savdolashuv bor', 'Savdolashuv bor')], default=None, max_length=99),
        ),
        migrations.AlterField(
            model_name='avto',
            name='xolati',
            field=models.CharField(choices=[('Avtosalon', 'Avtosalon')], default=None, max_length=99),
        ),
    ]
