# Generated by Django 5.0.1 on 2024-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0010_alter_avto_savdolashuv_alter_avto_xolati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='savdolashuv',
            field=models.CharField(choices=[('Savdolashuv bor', 'Savdolashuv bor'), ('Yoq', 'Yoq')], default=None, max_length=99),
        ),
        migrations.AlterField(
            model_name='avto',
            name='xolati',
            field=models.CharField(choices=[('Avtosalon', 'Avtosalon'), ('Ishlagan', 'Ishlagan')], default=None, max_length=99),
        ),
    ]
